install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb -o hugo.deb
  - sudo dpkg -i hugo.deb
  # v0.75.1

script:
  - ./deploy.sh

deploy:
  provider: pages
  cleanup: true
  github_token: $token_push  # Set in the settings page of your repository, as a secure variable
  local_dir: workplace/public
  on:
    branch: master